app:
  tickRateInSec: 30
  httpServerPort: 8081

discovery:
  refreshEveryMin: 1
#  consul:
#    host: CONSULSRV
#    port: 8500
#    timeoutInSec: 10
#    readConsistency: STALE
#    tags:
#     - couchbase-memcached
     #- cluster=CLUSTERNAME
     #- bucket=BUCKETNAME
  staticDns:
    clustername: cluster01
    host: couchbase01

service:
  type: MEMCACHED
  timeoutInSec: 60
  username: Administrator
  password: password

couchbaseStats:
  bucket: # API : /pools/default/buckets/MYBUCKET/nodes/MYNODE:PORT/stats
  xdcr: # API: replications/XDCR_UUID/MYBUCKET_SOURCE/MYBUCKET_DESTINATION/
